name: firebase_firestore_ng
description: Simple demo with AngularDart and Firebase Firestore
version: 0.0.2
homepage: https://github.com/oonid/firebase-firestore-ng
author: oon arfiandwi <oon.arfiandwi@gmail.com>
# this project is a fork from repository below
# homepage: https://github.com/Janamou/firebase-demo-ng
# author: Jana Moudrá <jana.moudra@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_forms: ^2.1.0
  firebase: ^5.0.0
  googleapis_auth: ^0.2.0
  service_worker: ^0.2.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.8.0
  test: ^1.6.0
